# apps/my-simple-app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-simple-app
  template:
    metadata:
      labels:
        app: my-simple-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-simple-app-service
spec:
  selector:
    app: my-simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80